# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='words',
        ),
        migrations.AddField(
            model_name='word',
            name='pages',
            field=models.ManyToManyField(to='search.Page'),
        ),
    ]
