# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160604_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='pageId',
            new_name='page_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='page_id',
        ),
        migrations.AlterField(
            model_name='word',
            name='pages',
            field=models.ManyToManyField(through='search.Match', to='search.Page'),
        ),
        migrations.AddField(
            model_name='match',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Page'),
        ),
    ]
